routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PaymentMethodController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/product/{product}', [ProductController::class, 'show'])->name('product');

Route::middleware(['auth'])->group(function () {
    // Cart routes
    Route::prefix('cart')->name('cart.')->group(function () {
        Route::get('/', [CartController::class, 'show'])->name('show');
        Route::post('/', [CartController::class, 'add'])->name('add');
        Route::delete('/', [CartController::class, 'removeAll'])->name('remove-all');
        Route::delete('/{product}', [CartController::class, 'remove'])->name('remove');
    });

    // Order routes
    Route::prefix('order')->name('order.')->group(function () {
        Route::get('/', [OrderController::class, 'index'])->name('index');
        Route::post('/', [OrderController::class, 'place'])->name('place');
        Route::get('/list', [OrderController::class, 'list'])->name('list');
        Route::get('/show/{order}', [OrderController::class, 'show'])->name('show');
    });

});

// Admin routes
Route::middleware(['auth', 'verify_admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/payment-methods', [PaymentMethodController::class, 'index'])->name('payment_methods');

    Route::resource('user', 'Admin\UserController');
    Route::resource('product', 'Admin\ProductController');

    Route::get('/order', [Admin\OrderController::class, 'index'])->name('order.index');
    Route::post('/order/approve/{order}', [Admin\OrderController::class, 'approve'])->name('order.approve');
    Route::get('/order/show/{order}', [Admin\OrderController::class, 'show'])->name('order.show');
});

Auth::routes();

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * App\Order
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order query()
 * @mixin \Eloquent
 * @property int $id
 * @property int $user_id
 * @property float $total
 * @property string $address
 * @property int $payment_method_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\PaymentMethod $paymentMethod
 * @property-read \App\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order whereAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order wherePaymentMethodId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order whereTotal($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order whereUserId($value)
 * @property int $status
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Order whereStatus($value)
 */
class Order extends Model
{
    protected $fillable = [
        'user_id', 'total', 'address', 'payment_method_id',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function paymentMethod(): BelongsTo
    {
        return $this->belongsTo(PaymentMethod::class);
    }

    public function items(): HasMany
    {
        return $this->hasMany(OrderItem::class);
    }

    public function statusText(): string
    {
        return $this->status ? 'Approved' : 'Pending';
    }

    public function approve(): void
    {
        $this->status = 1;
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Order;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class OrderController extends Controller
{
    public function index(): View
    {
        $orders = Order::orderByDesc('id')->paginate();
        $orderCount = Order::count();

        return view('admin.order.index', compact('orders', 'orderCount'));
    }

    public function approve(Order $order): RedirectResponse
    {
        $order->approve();
        $order->save();

        return \Redirect::back()->with('success', 'Order approved.');
    }

    public function show(Order $order): View
    {
        return view('admin.order.show', compact('order'));
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PlaceOrderRequest;
use App\Order;
use App\OrderItem;
use App\PaymentMethod;
use App\Services\Cart;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\View\View;

class OrderController extends Controller
{
    public function index(Cart $cart): View
    {
        $paymentMethods = PaymentMethod::all();

        return view('order.index', compact('cart', 'paymentMethods'));
    }

    public function place(PlaceOrderRequest $request, Cart $cart): RedirectResponse
    {
        $data = $request->validated();
        $data['user_id'] = \Auth::id();
        $data['total'] = $cart->getTotal();

        DB::beginTransaction();

        try {
            $order = Order::create($data);

            foreach ($cart->getItems() as $item) {
                OrderItem::create([
                    'order_id' => $order->id,
                    'name' => $item->product->name,
                    'image' => $item->product->image,
                    'price' => $item->product->price,
                    'description' => $item->product->description,
                    'quantity' => $item->quantity,
                ]);
                $cart->remove($item->product);
            }

            $cart->removeAll();

            DB::commit();
        } catch (\Exception $e) {
            DB::rollBack();

            Log::error('Order Place', [
                'message' => $e->getMessage(),
            ]);

            return \Redirect::back()->with('error', 'Can not place order. Please try again');
        }

        return \Redirect::route('order.show', [$order->id])->with('success', 'Order placed.');
    }

    public function list(): View
    {
        $orders = Order::where('user_id', \Auth::id())->orderByDesc('id')->paginate();
        $orderCount = Order::where('user_id', \Auth::id())->count();

        return view('order.list', compact('orders', 'orderCount'));
    }

    public function show(Order $order): View
    {
        $order->load('items');

        return view('order.show', compact('order'));
    }
}

resources/views/order/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1>
                    Place Order
                    <a class="btn btn-secondary float-right" href="{{ route('cart.show') }}">Back to Cart</a>
                </h1>
                @include('success_message')
                @include('validation_errors')

                @if($cart->getItems()->count())
                    <form class="card" action="{{ route('order.place') }}" method="POST">
                        @csrf
                        <div class="card-body">
                            <h5>Order items</h5>
                            <ul>
                            @foreach($cart->getItems() as $item)
                                <li>{{ $item->product->name }} x{{ $item->quantity }} ({{ $item->total() }} TRY)
                                </li>
                            @endforeach
                            </ul>
                            <p>Total: <b>{{ $cart->getTotal() }} TRY</b></p>
                            <div class="form-group">
                                <label for="address">Address</label>
                                <textarea name="address" id="address" class="form-control"
                                          placeholder="Where to deliver">{{ old('address') }}</textarea>
                            </div>

                            <div class="form-group">
                                <label for="payment-method">Payment Method</label>
                                <select name="payment_method_id" id="payment-method" class="form-control">
                                    @foreach($paymentMethods as $method)
                                        <option value="{{ $method->id }}">{{ $method->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <button class="float-right btn btn-primary">Place Order</button>
                            </div>
                        </div>
                    </form>
                @else
                    <div class="alert alert-info">Cart is empty.</div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/order/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1>Orders ({{ $orderCount }})</h1>

                @if ($orders->isEmpty())
                    <div class="alert alert-info">No orders.</div>
                @else
                    <table class="table table-bordered bg-white">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Items</th>
                            <th>Total</th>
                            <th>Date</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($orders as $order)
                            <tr>
                                <td>{{ $order->id }}</td>
                                <td>{{ $order->items->count() }}</td>
                                <td>{{ $order->total }} TRY</td>
                                <td>{{ $order->created_at }}</td>
                                <td>
                                    <a href="{{ route('order.show', [$order->id]) }}"
                                       class="btn btn-primary btn-sm">Details</a>
                                    @if ($order->status)
                                        <button class="btn btn-success btn-sm" disabled>Approved</button>
                                    @else
                                        <button class="btn btn-warning btn-sm" disabled>Pending</button>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        @if ($orders->hasPages())
                            <tfoot>
                            <tr>
                                <td colspan="5">{{ $orders->links() }}</td>
                            </tr>
                            </tfoot>
                        @endif
                    </table>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/order/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1>Order Detail #{{ $order->id }}</h1>

                @include('success_message')

                <div class="card">
                    <div class="card-body">
                        <h5>Info</h5>
                        <ul>
                            <li><b>Address:</b> {{ $order->address }}</li>
                            <li><b>Payment Method:</b> {{ $order->paymentMethod->name }}</li>
                            <li><b>Status:</b> <span class="badge badge-{{ $order->status ? 'success': 'warning' }}">{{ $order->statusText() }}</span></li>
                            <li><b>Created at:</b> {{ $order->created_at }}</li>
                        </ul>

                        <h5>Products ({{ $order->items->count() }})</h5>
                        <table class="table table-bordered bg-white">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Quantity</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($order->items as $item)
                                <tr>
                                    <td>{{ $item->id }}</td>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ $item->price }} TRY</td>
                                    <td>{{ $item->quantity }}</td>

                                </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>Total</th>
                                <th colspan="3">{{ $order->total }} TRY</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>

                <br>
                <a href="{{ route('order.list') }}" class="btn btn-secondary">Back to Orders</a>
            </div>
        </div>
    </div>
@endsection